// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	MenuPermissions     string
	Menus               string
	Permissions         string
	RoleMenuPermissions string
	Roles               string
	Users               string
}{
	MenuPermissions:     "menu_permissions",
	Menus:               "menus",
	Permissions:         "permissions",
	RoleMenuPermissions: "role_menu_permissions",
	Roles:               "roles",
	Users:               "users",
}
