// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("CartToProductUsingProduct", testCartToOneProductUsingProduct)
	t.Run("CartToUserUsingUser", testCartToOneUserUsingUser)
	t.Run("MenuPermissionToMenuUsingMenu", testMenuPermissionToOneMenuUsingMenu)
	t.Run("MenuPermissionToPermissionUsingPermission", testMenuPermissionToOnePermissionUsingPermission)
	t.Run("OrderToProductUsingProduct", testOrderToOneProductUsingProduct)
	t.Run("OrderToUserUsingUser", testOrderToOneUserUsingUser)
	t.Run("ProductTagToProductUsingProduct", testProductTagToOneProductUsingProduct)
	t.Run("ProductTagToTagUsingTag", testProductTagToOneTagUsingTag)
	t.Run("RoleMenuPermissionToMenuPermissionUsingMenuPermission", testRoleMenuPermissionToOneMenuPermissionUsingMenuPermission)
	t.Run("RoleMenuPermissionToRoleUsingRole", testRoleMenuPermissionToOneRoleUsingRole)
	t.Run("UserToRoleUsingRole", testUserToOneRoleUsingRole)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("MenuPermissionToRoleMenuPermissions", testMenuPermissionToManyRoleMenuPermissions)
	t.Run("MenuToMenuPermissions", testMenuToManyMenuPermissions)
	t.Run("PermissionToMenuPermissions", testPermissionToManyMenuPermissions)
	t.Run("ProductToCarts", testProductToManyCarts)
	t.Run("ProductToOrders", testProductToManyOrders)
	t.Run("ProductToProductTags", testProductToManyProductTags)
	t.Run("RoleToRoleMenuPermissions", testRoleToManyRoleMenuPermissions)
	t.Run("RoleToUsers", testRoleToManyUsers)
	t.Run("TagToProductTags", testTagToManyProductTags)
	t.Run("UserToCarts", testUserToManyCarts)
	t.Run("UserToOrders", testUserToManyOrders)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("CartToProductUsingCarts", testCartToOneSetOpProductUsingProduct)
	t.Run("CartToUserUsingCarts", testCartToOneSetOpUserUsingUser)
	t.Run("MenuPermissionToMenuUsingMenuPermissions", testMenuPermissionToOneSetOpMenuUsingMenu)
	t.Run("MenuPermissionToPermissionUsingMenuPermissions", testMenuPermissionToOneSetOpPermissionUsingPermission)
	t.Run("OrderToProductUsingOrders", testOrderToOneSetOpProductUsingProduct)
	t.Run("OrderToUserUsingOrders", testOrderToOneSetOpUserUsingUser)
	t.Run("ProductTagToProductUsingProductTags", testProductTagToOneSetOpProductUsingProduct)
	t.Run("ProductTagToTagUsingProductTags", testProductTagToOneSetOpTagUsingTag)
	t.Run("RoleMenuPermissionToMenuPermissionUsingRoleMenuPermissions", testRoleMenuPermissionToOneSetOpMenuPermissionUsingMenuPermission)
	t.Run("RoleMenuPermissionToRoleUsingRoleMenuPermissions", testRoleMenuPermissionToOneSetOpRoleUsingRole)
	t.Run("UserToRoleUsingUsers", testUserToOneSetOpRoleUsingRole)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("CartToProductUsingCarts", testCartToOneRemoveOpProductUsingProduct)
	t.Run("CartToUserUsingCarts", testCartToOneRemoveOpUserUsingUser)
	t.Run("MenuPermissionToMenuUsingMenuPermissions", testMenuPermissionToOneRemoveOpMenuUsingMenu)
	t.Run("MenuPermissionToPermissionUsingMenuPermissions", testMenuPermissionToOneRemoveOpPermissionUsingPermission)
	t.Run("OrderToProductUsingOrders", testOrderToOneRemoveOpProductUsingProduct)
	t.Run("OrderToUserUsingOrders", testOrderToOneRemoveOpUserUsingUser)
	t.Run("ProductTagToProductUsingProductTags", testProductTagToOneRemoveOpProductUsingProduct)
	t.Run("ProductTagToTagUsingProductTags", testProductTagToOneRemoveOpTagUsingTag)
	t.Run("RoleMenuPermissionToMenuPermissionUsingRoleMenuPermissions", testRoleMenuPermissionToOneRemoveOpMenuPermissionUsingMenuPermission)
	t.Run("RoleMenuPermissionToRoleUsingRoleMenuPermissions", testRoleMenuPermissionToOneRemoveOpRoleUsingRole)
	t.Run("UserToRoleUsingUsers", testUserToOneRemoveOpRoleUsingRole)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("MenuPermissionToRoleMenuPermissions", testMenuPermissionToManyAddOpRoleMenuPermissions)
	t.Run("MenuToMenuPermissions", testMenuToManyAddOpMenuPermissions)
	t.Run("PermissionToMenuPermissions", testPermissionToManyAddOpMenuPermissions)
	t.Run("ProductToCarts", testProductToManyAddOpCarts)
	t.Run("ProductToOrders", testProductToManyAddOpOrders)
	t.Run("ProductToProductTags", testProductToManyAddOpProductTags)
	t.Run("RoleToRoleMenuPermissions", testRoleToManyAddOpRoleMenuPermissions)
	t.Run("RoleToUsers", testRoleToManyAddOpUsers)
	t.Run("TagToProductTags", testTagToManyAddOpProductTags)
	t.Run("UserToCarts", testUserToManyAddOpCarts)
	t.Run("UserToOrders", testUserToManyAddOpOrders)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("MenuPermissionToRoleMenuPermissions", testMenuPermissionToManySetOpRoleMenuPermissions)
	t.Run("MenuToMenuPermissions", testMenuToManySetOpMenuPermissions)
	t.Run("PermissionToMenuPermissions", testPermissionToManySetOpMenuPermissions)
	t.Run("ProductToCarts", testProductToManySetOpCarts)
	t.Run("ProductToOrders", testProductToManySetOpOrders)
	t.Run("ProductToProductTags", testProductToManySetOpProductTags)
	t.Run("RoleToRoleMenuPermissions", testRoleToManySetOpRoleMenuPermissions)
	t.Run("RoleToUsers", testRoleToManySetOpUsers)
	t.Run("TagToProductTags", testTagToManySetOpProductTags)
	t.Run("UserToCarts", testUserToManySetOpCarts)
	t.Run("UserToOrders", testUserToManySetOpOrders)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("MenuPermissionToRoleMenuPermissions", testMenuPermissionToManyRemoveOpRoleMenuPermissions)
	t.Run("MenuToMenuPermissions", testMenuToManyRemoveOpMenuPermissions)
	t.Run("PermissionToMenuPermissions", testPermissionToManyRemoveOpMenuPermissions)
	t.Run("ProductToCarts", testProductToManyRemoveOpCarts)
	t.Run("ProductToOrders", testProductToManyRemoveOpOrders)
	t.Run("ProductToProductTags", testProductToManyRemoveOpProductTags)
	t.Run("RoleToRoleMenuPermissions", testRoleToManyRemoveOpRoleMenuPermissions)
	t.Run("RoleToUsers", testRoleToManyRemoveOpUsers)
	t.Run("TagToProductTags", testTagToManyRemoveOpProductTags)
	t.Run("UserToCarts", testUserToManyRemoveOpCarts)
	t.Run("UserToOrders", testUserToManyRemoveOpOrders)
}
