// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Carts               string
	MenuPermissions     string
	Menus               string
	Orders              string
	Permissions         string
	ProductTags         string
	Products            string
	RoleMenuPermissions string
	Roles               string
	Tags                string
	Users               string
}{
	Carts:               "carts",
	MenuPermissions:     "menu_permissions",
	Menus:               "menus",
	Orders:              "orders",
	Permissions:         "permissions",
	ProductTags:         "product_tags",
	Products:            "products",
	RoleMenuPermissions: "role_menu_permissions",
	Roles:               "roles",
	Tags:                "tags",
	Users:               "users",
}
