// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("MenuPermissions", testMenuPermissionsUpsert)

	t.Run("Menus", testMenusUpsert)

	t.Run("Permissions", testPermissionsUpsert)

	t.Run("RoleMenuPermissions", testRoleMenuPermissionsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("Users", testUsersUpsert)
}
