// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("RolePermissionToPermissionUsingPermission", testRolePermissionToOnePermissionUsingPermission)
	t.Run("RolePermissionToRoleUsingRole", testRolePermissionToOneRoleUsingRole)
	t.Run("UserToRoleUsingRole", testUserToOneRoleUsingRole)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("PermissionToRolePermissions", testPermissionToManyRolePermissions)
	t.Run("RoleToRolePermissions", testRoleToManyRolePermissions)
	t.Run("RoleToUsers", testRoleToManyUsers)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("RolePermissionToPermissionUsingRolePermissions", testRolePermissionToOneSetOpPermissionUsingPermission)
	t.Run("RolePermissionToRoleUsingRolePermissions", testRolePermissionToOneSetOpRoleUsingRole)
	t.Run("UserToRoleUsingUsers", testUserToOneSetOpRoleUsingRole)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("RolePermissionToPermissionUsingRolePermissions", testRolePermissionToOneRemoveOpPermissionUsingPermission)
	t.Run("RolePermissionToRoleUsingRolePermissions", testRolePermissionToOneRemoveOpRoleUsingRole)
	t.Run("UserToRoleUsingUsers", testUserToOneRemoveOpRoleUsingRole)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("PermissionToRolePermissions", testPermissionToManyAddOpRolePermissions)
	t.Run("RoleToRolePermissions", testRoleToManyAddOpRolePermissions)
	t.Run("RoleToUsers", testRoleToManyAddOpUsers)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("PermissionToRolePermissions", testPermissionToManySetOpRolePermissions)
	t.Run("RoleToRolePermissions", testRoleToManySetOpRolePermissions)
	t.Run("RoleToUsers", testRoleToManySetOpUsers)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("PermissionToRolePermissions", testPermissionToManyRemoveOpRolePermissions)
	t.Run("RoleToRolePermissions", testRoleToManyRemoveOpRolePermissions)
	t.Run("RoleToUsers", testRoleToManyRemoveOpUsers)
}
